;;; figlet-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from figlet.el

(autoload 'figlet "figlet" "\
Pass a string through figlet and insert the output at
point. Use a prefix arg to be promted for a font.

(fn STRING)" t)
(autoload 'figlet-comment "figlet" "\
Insert a figlet string just as `figlet' would but comment the
result (using `comment-region')

(fn STRING)" t)
(autoload 'figlet-figletify-region "figlet" "\
Convert the region into a figlet string.

(fn START END)" t)
(autoload 'figlet-figletify-region-comment "figlet" "\
Convert the region into a figlet string as with
`figlet-figletify-region' but comment it out too.

(fn START END)" t)
(autoload 'figlet-preview-fonts "figlet" "\
View an example of each font in a new buffer.

(fn &optional TEXT)" t)
(register-definition-prefixes "figlet" '("figlet-"))

;;; End of scraped data

(provide 'figlet-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; figlet-autoloads.el ends here
